### ISSUE TITLE
Include adminer designs

### ISSUE THREAD

**Issue by mikehaertl** [TimWolla/docker-adminer#1]
It would be great if the available adminer designs could be included into the image and activated by some environment flag, e.g. `ADMINER_DESIGN='nicu'`.

Of course we could also map our `adminer.css` into the image at runtime - but that's another step required when all we need is a quick admin interface for our DB.

**Comment by mikehaertl** [comment]
@TimWolla Any opinion on this?

**Comment by TimWolla** [comment]
I'm currently not at home, this issue is not forgotten.

Am 13.03.2017 09:20 schrieb "Michael Härtl" <notifications@github.com>:

**Comment by TimWolla** [comment]
@mikehaertl Without looking to deep into it: I suspect it being non-trivial (we would need an entrypoint script, that creates symlinks or something like that and I would need to ensure that the CSS files are up to date) for no **real** benefit. Adminer designs are CSS only, without providing real functionality, so this looks primarily like a personal preference thing.

Do you personally see a benefit in this issue or can we agree on a “no”?

**Comment by mikehaertl** [comment]
Well, I'd consider i as nice to have. I find the default style not so good and to verbose. It would be optional, so if the respective env var is not set, there's nothing to do. Actually I don't think that the entry script is really so difficult. I could even give it a try, if you want.

Keeping the CSS up to date could be a bit more tricky, though. On the other hand it doesn't seem to change often as adminer is quite "stable" in this regard and doesn't seem to modify it's CSS classes with new releases.

**Comment by TimWolla** [comment]
> I could even give it a try, if you want.

Okay. I'm willing to support it under the following conditions:

- Download the „Source Code“ .tar.gz of the appropriate adminer version from here: https://github.com/vrana/adminer/releases
- Extract the designs into an appropriate folder
- Delete the .tar.gz afterwards
- Last line of the script is `exec "$@"`

**Comment by mikehaertl** [comment]
Sure, just one thing: The designs are only available as direct links to the respective `adminer.css` files, e.g. https://raw.githubusercontent.com/vrana/adminer/master/designs/hever/adminer.css. They are linked directly from their homepage here https://www.adminer.org/#extras.

So the task boils down to:

 * From the `Dockerfile` download each design to a `css/` directory and give it a unique name e.g. `css/hever.css`
* The entryscript only has to check if `ADMINER_DESIGN` is set and create a symlink e.g. from `css/hever.css` to `adminer.css`
* At the end of the script we call `exec "$@"` and configure the script as `ENTRYPOINT` in `Dockerfile`

Anything missing?

**Comment by TimWolla** [comment]
> The designs are only available

This is incorrect. Read the first bullet point of my previous comment. You can find the designs in the `/adminer-*/designs/` folder of the .tar.gz archive

**Comment by mikehaertl** [comment]
I did read it but was confused because I could not find a link to any .tar.gz file on the page (maybe I'm blind). But now I see that there's a link to "source" as .zip and the designs are there, too. Even better then. Of course we'd remove that after copying the style files.

Any other comments to the above approach?

**Comment by mikehaertl** [comment]
Another thing: Where did you find the hash signature? We could replace the current download with the zip package and also use the `adminer.php` from there.

**Comment by TimWolla** [comment]
> I did read it but was confused because I could not find a link to any .tar.gz file on the page (maybe I'm blind). But now I see that there's a link to "source" as .zip and the designs are there, too. Even better then. Of course we'd remove that after copying the style files.

It's on the very same page: 
![grafik](https://cloud.githubusercontent.com/assets/209270/24308811/c544f416-10c9-11e7-8337-82f88cac9fcd.png). A tar archive has the advantage that tar is already installed anyway.

> Another thing: Where did you find the hash signature? We could replace the current download with the zip package and also use the adminer.php from there.

If I'm not mistaken the generated adminer.php does not exist in the repository and thus it does not appear in the archive. The hash was generated by manually downloading the file and running `sha256sum`. I am not aware of any published hashes.

**Comment by mikehaertl** [comment]
> It's on the very same page

Yes, I found it meanwhile. I thought you where referring to the adminer home page.

> A tar archive has the advantage that tar is already installed anyway.

Right, will use tar of course.

> If I'm not mistaken the generated adminer.php does not exist in the repository and thus it does not appear in the archive.

Yes, that's what I found out now, too. So we let the adminer download unchanged.

> The hash was generated by manually downloading the file and running sha256sum

Ok, that's what I'll do now, too. I've just seen it at the [install script](https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md) for composer, where they also download the sig from a [different site](https://composer.github.io/pubkeys.html). But it seems github does not provide such a feature.

**Comment by mikehaertl** [comment]
@TimWolla Thanks for merging. Any estimate when we will see this in the `adminer:latest` build on docker hub?

**Comment by TimWolla** [comment]
@mikehaertl Updates to Docker hub must pass through the official vetting process in docker-library/official-images. See my previous PRs: https://github.com/docker-library/official-images/pulls?q=is%3Apr+label%3Alibrary%2Fadminer+is%3Aclosed

I did not create a PR yet, because this change is non-urgent and I'd like to get out plugin support before taking up the Docker maintainer's time.

**Comment by mtpultz** [comment]
@mikehaertl if I understand this I should be able to just set `ENV ADMINER_DESIGN=pepa-linha` in my dockerfile, and the theme should update?  I can't tell if this has been pushed into latest yet, but I'm assuming it hasn't since this doesn't seem to work if I have it correct.

**Comment by mtpultz** [comment]
Sorry @TimWolla didn't mean to side step you.  I can definitely do that - https://github.com/TimWolla/docker-adminer/issues/12
