### ISSUE TITLE
Update adminer to 4.8.1

### ISSUE THREAD

**Issue by gloryknight** [TimWolla/docker-adminer#103]
New release: https://github.com/vrana/adminer/releases/tag/v4.8.1

**Comment by wutsch0** [comment]
there is already a PR, but it needs approval:
https://github.com/TimWolla/docker-adminer/pull/102

**Comment by gloryknight** [comment]
Why the pull request is not jet merged?
I am affected by a bug in 4.8.0 when used with postgresql.
Can I help?

**Comment by TimWolla** [comment]
Awesome, GitHub messed up my watch settings for this repository for some reason and thus I missed this issue / PR. I'll handle this latter. Please apologize the delay!

**Comment by gloryknight** [comment]
Thank you for the update.
