### ISSUE TITLE
Invalid request (Unsupported SSL request)

### ISSUE THREAD

**Issue by SunSDSE** [TimWolla/docker-adminer#105]
I have a little MariaDB & Adminer running on a Raspberry Pi Swarm.
The service has been operating great, until this morning when I have been unable to make connection to the service.

Starting and restarting as well as recreating the service is not changing the behavior.  All requests are reporting "Invalid request (Unsupported SSL request)" in the adminer service logs.   

Every connection in the log is reporting the following:

`MariaDB_adminer.1.igdvfhe5hll9@RPi43    | [Thu Jul 29 18:41:36 2021] [::ffff:10.0.0.17]:58750 Accepted
MariaDB_adminer.1.igdvfhe5hll9@RPi43    | [Thu Jul 29 18:41:36 2021] [::ffff:10.0.0.17]:58750 Invalid request (Unsupported SSL request)
MariaDB_adminer.1.igdvfhe5hll9@RPi43    | [Thu Jul 29 18:41:36 2021] [::ffff:10.0.0.17]:58750 Closing
`

The MariaDB and Adminer docker services is created using the following docker-compose.yml:
`
version: '3.7'
services:
  mariadb:
    image: mariadb:latest
    environment:
       MARIADB_USER: "MySqlUser"
       MARIADB_PASSWORD: "MySecurePasswd"
       MARIADB_ROOT_PASSWORD: "MySecurePasswd"
       MARIADB_DATABASE: "HomeDB"
       TZ: "PDT8PST"
    logging:
       driver: syslog
       options:
          tag: "{{.DaemonName}}(image={{.ImageName}};name={{.Name}};id={{.ID}})"
    networks:
       - MariaDB_mariadb-net
    ports:
       # Published Port : Source Port
       - "3306:3306"
    volumes:
       - /mnt/home/MariaDB/data:/var/lib/mysql
       - /mnt/home/MariaDB/conf:/var/lib/conf
       - /mnt/home/MariaDB/log:/var/log/mysql
       - /mnt/home/nginx/certbot/conf/live/xxxxxURIxxxxxxx:/etc/letsencrypt/certs
       - /mnt/home/MariaDB/conf/my.cnf:/etc/mysql/my.cnf

  adminer:
    # depends_on:
    #  - testdb
    image: adminer
    ports:
      # Published Port : Source Port
      - '8085:8080'
    environment:
      - PMA_HOST=mariadb:3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Gextuam10
    networks:
      - MariaDB_mariadb-net
    deploy:
      placement:
        constraints: [node.role == worker]
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=MariaDB_mariadb-net"
        - "traefik.http.routers.adminer.rule=Host(`dbadmin.example`)"
        - "traefik.http.routers.adminer.tls=true"
        - "traefik.http.routers.adminer.tls.certresolver=default"
        - "traefik.http.routers.adminer.entrypoints=websecure"
        - "traefik.http.services.adminer.loadbalancer.server.port=8080"
networks:
  MariaDB_mariadb-net:
    driver: overlay
`

**Comment by TimWolla** [comment]
I've not seen this error message before, but could it be that your web browser sends direct encrypted HTTPS requests to Adminer? For example because of the recent features to upgrade all connections to TLS encrypted connections?

**Comment by SunSDSE** [comment]
The obvious... My Safari browser shifted to https with out my noticing

**Comment by SunSDSE** [comment]
Is there any documentation on how to integrate LetsEncrypt Certs with Adminer?

**Comment by TimWolla** [comment]
> Is there any documentation on how to integrate LetsEncrypt Certs with Adminer?

The image itself does not support TLS. Use a reverse proxy or FastCGI gateway of your choice (e.g. nginx) to proxy the requests to Adminer. These usually support TLS one way or another.

**Comment by SunSDSE** [comment]
Thanks, That I have running with nginx, Thank you for the help!
