### ISSUE TITLE
Does not include designs from submodules

### ISSUE THREAD

**Issue by Reintjuu** [TimWolla/docker-adminer#106]
When setting a theme that is included as a submodule in the original Adminer repo (https://github.com/vrana/adminer/tree/master/designs) through `ADMINER_DESIGN`, Adminer falls back to the original theme. https://github.com/Niyko/Hydra-Dark-Theme-for-Adminer/issues/13 lists a few possible solutions but I think this Dockerfile should include all themes listed in the original repo.

**Comment by TimWolla** [comment]
Ugh, thanks for the report. I really want to avoid cloning the git repository within my Dockerfile. The GitHub generated archives are just so much easier to consume.

**Comment by Reintjuu** [comment]
Woah, thanks for the quick reply! If you need help in any way or need a PR review, don't hesitate to ask.

**Comment by TimWolla** [comment]
@Reintjuu Feel free to have a look at #107. It worked in my tests, but I'm _really_ not happy with that solution.

**Comment by X1pheR** [comment]
I just faced this problem. Is there still being worked on a solution?

**Comment by TimWolla** [comment]
@X1pheR Sorry, I lost track of #107. I've created a reminder to look into that once more.

**Comment by X1pheR** [comment]
Thanks. If it completes, will this issue be updated? I'll just wait then ;)

**Comment by kyro-dev** [comment]
I'm still facing this issue, are there any fixes?

**Comment by TimWolla** [comment]
> I'm still facing this issue, are there any fixes?

https://github.com/docker-library/official-images/pull/11984
