### ISSUE TITLE
Current version of Adminer generates warnings under PHP 8 when submitting custom queries

### ISSUE THREAD

**Issue by pospjan** [TimWolla/docker-adminer#108]
What was the reason behind PHP update in https://github.com/TimWolla/docker-adminer/commit/e1e324eeeba2c7e061603df365b485d9661902f6? It seems that Adminer isn't fully supporting PHP 8 while doing custom queries:

<img width="860" alt="Screenshot 2021-09-27 at 20 20 12" src="https://user-images.githubusercontent.com/49492371/134966580-e8d331df-0b1d-4bc0-b165-4ed620483a8f.png">

**Comment by TimWolla** [comment]
> What was the reason behind PHP update

No particular reason, other than not trailing behind PHP releases. There were quite a few PHP 8 fixes and PHP 8 is almost one year old by now, so I assumed that it would be properly supported now.

> It seems that Adminer isn't fully supporting PHP 8 while doing custom queries:

Would you mind filing an upstream issue at https://sourceforge.net/p/adminer/bugs-and-features/? I can revert to PHP 7.4 if necessary, but the bug needs to be fixed nonetheless.

**Comment by TimWolla** [comment]
A similar issue has already been reported upstream as it looks like: https://sourceforge.net/p/adminer/bugs-and-features/801/

**Comment by pospjan** [comment]
@TimWolla Hi Tim, thanks a lot for such a quick response. I will try to fix this particular Adminer's problem on my own and send a PR to the upstream.

**Comment by TimWolla** [comment]
see also: https://github.com/TimWolla/docker-adminer/pull/85#issuecomment-936154226
