### ISSUE TITLE
How to mount the proper Docker volume for plugin changes?

### ISSUE THREAD

**Issue by ElleshaHackett** [TimWolla/docker-adminer#112]
I want to start using plugins. Such as https://raw.githubusercontent.com/vrana/adminer/master/plugins/login-otp.php and https://raw.githubusercontent.com/vrana/adminer/master/plugins/login-servers.php. But in both cases I can enable it only using `environment: ADMINER_PLUGINS` in my docker-compose file but how do I actually change the related plugin settings? I want to use `AdminerLoginServers` to enable support for mysql only and disable others. 

For the OTP plugin, https://www.adminer.org/en/plugins/otp/ I want to change `JXLNdeZb/uKGDw==` as shown in the example.

**Comment by TimWolla** [comment]
Sorry, I somehow missed the email notification about this:

You will either need to build a custom Docker image with the files added, or use a bind mount at `/var/www/html/plugins-enabled/` to add the plugin files with the appropriate configuration. See: https://github.com/docker-library/docs/blob/master/adminer/content.md#loading-plugins
