### ISSUE TITLE
headers already sent by in /var/www/html/adminer.php on line 1447

### ISSUE THREAD

**Issue by palansher** [TimWolla/docker-adminer#126]
Hello!

just report:

on http://adminer.localhost:8080/?server=gt-mysql%3A3306&username=root&db=gt-dev-db-genkel&user=genkel&host=localhost

I gets brocken page:

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/adminer.php:1734) in /var/www/html/adminer.php on line 1447

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/adminer.php:1734) in /var/www/html/adminer.php on line 1447

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/adminer.php:1734) in /var/www/html/adminer.php on line 1447

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/adminer.php:1734) in /var/www/html/adminer.php on line 1447

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/adminer.php:1734) in /var/www/html/adminer.php on line 1447

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/adminer.php:1734) in /var/www/html/adminer.php on line 1447

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/adminer.php:1734) in /var/www/html/adminer.php on line 1448

![image](https://user-images.githubusercontent.com/24850253/179216297-47d00b92-c5c4-4de5-8f1b-c24881aa1a5d.png)

**Comment by TimWolla** [comment]
The “headers already sent by” is caused by the very first warning in that list, but that one is not readable.

**Comment by palansher** [comment]
Cannot reproduce now :) 
So let's close, and I'll [re]open if meet the same.

Thanks for your work!

**Comment by TimWolla** [comment]
It's very likely that the bug would need to be reported upstream anyway. I'm not developing Adminer, I'm just packaging it.
