### ISSUE TITLE
None of the supported PHP extensions (SQLSRV, MSSQL, PDO_DBLIB) are available.

### ISSUE THREAD

**Issue by S1L3NTANG3L** [TimWolla/docker-adminer#131]
Hi, I'm trying to connect a ms sql server but getting this, you maybe know where/how I can fix this?

**Comment by TimWolla** [comment]
This is likely a regression of #129.

**Comment by TimWolla** [comment]
@S1L3NTANG3L Can you please try the updated Dockerfile in #129? I just pushed a possible fix. I don't use Microsoft's SQL Server myself.

**Comment by ewag** [comment]
I tested your Dockerfile out, and it worked just fine. Was able to do everything I could normally do in adminer on my mssql databases. Query, create a DB, run a script, etc.

**Comment by S1L3NTANG3L** [comment]
What is the current version of the Docker?

**Comment by ewag** [comment]
> What is the current version of the Docker?

I cloned the repo, and used the pull request (#129 )to build a container I could test in my kubernetes cluster where I have adminer running.

**Comment by TimWolla** [comment]
Thanks for the feedback, I've now created the PR at docker-library/official-images, see above.

**Comment by TimWolla** [comment]
Already merged, the updated images should be available soon on Docker Hub.
