### ISSUE TITLE
vulnerability issue

### ISSUE THREAD

**Issue by Lohithsl** [TimWolla/docker-adminer#140]
we are getting below vulnerability issues

1.  Application of regex matched file found in container: file=/var/www/html/designs/pepa-linha-dark/.git regexp=.*/\.git$ 
2. Application of regex matched file found in container: file=/var/www/html/designs/hydra/.git regexp=.*/\.git$ 

to remove these getting permission denied error

**Comment by TimWolla** [comment]
I'm afraid this report lacks detail and thus is not actionable.

**Comment by Lohithsl** [comment]
when pull the Docker image for adminer:latest under /var/www/html/designs/pepa-linha-dark/ & /var/www/html/designs/hydra path we can find .git file, so we are getting vulnerability. If we remove these .git files docker container will not run properly any reason or solution for this issue?

**Comment by TimWolla** [comment]
I don't see how the two existence of the two files is a vulnerability.
