### ISSUE TITLE
adminer:4.8.1 | adminer:4.8.1-standalone missing ping  curl tools

### ISSUE THREAD

**Issue by geekyouth** [TimWolla/docker-adminer#148]
![image](https://github.com/TimWolla/docker-adminer/assets/12899262/e7f255f4-9aeb-47df-966b-178440021de9)

![image](https://github.com/TimWolla/docker-adminer/assets/12899262/f4147046-c279-4847-a479-f2fdc5637b41)

![image](https://github.com/TimWolla/docker-adminer/assets/12899262/c00fc2de-1453-4305-9ae6-d1dd47acc045)

**Comment by TimWolla** [comment]
Please install them yourself if you need them. They are not required for the correct operation of this image and thus not explicitly included, unless pulled in by something else.
