### ISSUE TITLE
Security: PHP version

### ISSUE THREAD

**Issue by JulianRueck** [TimWolla/docker-adminer#149]
PHP version 7.4.33 contains critical vulnerabilities. Any reason not to update to a later version?

**Comment by JulianRueck** [comment]
My sys ad gave me a heads up on critical vulnerabilities on port 8080. I can't find any critical ones myself, so I do apologise for that statement. Though his system probably went off on the fact that it's EOL, and potentially will get critical in the future. Any reason not update to a non EOL version of PHP?

**Comment by TimWolla** [comment]
> Any reason not update to a non EOL version of PHP?

Please see #132 and possibly #147.
