### ISSUE TITLE
Invalid CSRF token. Send the form again. If you did not send this request from Adminer then close this page.

### ISSUE THREAD

**Issue by juhntao** [TimWolla/docker-adminer#150]
docker-compose.yml
version: "3.7"
services:
    mysql:
      image: "mysql:8.0"
      environment:
        - "MYSQL_ROOT_PASSWORD=EvH6Qpw0uTTNPpZQ"
        - "MYSQL_ROOT_HOST=%"
    adminer:
      image: adminer:latest
      ports:
        - "8080:8080"

create a dabasebase throw exception Invalid CSRF token. Send the form again. If you did not send this request from Adminer then close this page.

docker logs
[Mon Aug  7 05:51:32 2023] PHP 7.4.33 Development Server (http://[::]:8080) started
[Mon Aug  7 05:51:38 2023] [::ffff:139.196.86.85]:49621 Accepted
[Mon Aug  7 05:51:38 2023] PHP Warning:  session_start(): open(/var/lib/php/sessions/sess_qpjg2j3vpej0a1smdhu237hiep, O_RDWR) failed: Permission denied (13) in /var/www/html/adminer.php on line 172
[Mon Aug  7 05:51:38 2023] PHP Warning:  session_start(): Failed to read session data: files (path: /var/lib/php/sessions) in /var/www/html/adminer.php on line 172
[Mon Aug  7 05:51:38 2023] PHP Warning:  session_start(): open(/var/lib/php/sessions/sess_c6pnqlgnhnbb6687ja0n4det7s, O_RDWR) failed: Permission denied (13) in /var/www/html/adminer.php on line 72
[Mon Aug  7 05:51:38 2023] PHP Warning:  session_start(): Failed to read session data: files (path: /var/lib/php/sessions) in /var/www/html/adminer.php on line 72
[Mon Aug  7 05:51:38 2023] [::ffff:139.196.86.85]:49621 [403]: GET /?server=mysql&username=root
[Mon Aug  7 05:51:38 2023] [::ffff:139.196.86.85]:49621 Closing
[Mon Aug  7 05:51:38 2023] [::ffff:139.196.86.85]:49622 Accepted
[Mon Aug  7 05:51:39 2023] [::ffff:139.196.86.85]:49623 Accepted

**Comment by TimWolla** [comment]
I'm unable to reproduce this issue. You should investigate why this error message is emitted:


> [Mon Aug 7 05:51:38 2023] PHP Warning: session_start(): open(/var/lib/php/sessions/sess_c6pnqlgnhnbb6687ja0n4det7s, O_RDWR) failed: Permission denied (13) in /var/www/html/adminer.php on line 72
