### ISSUE TITLE
Sub Queries in search are not executed

### ISSUE THREAD

**Issue by kale1d0code** [TimWolla/docker-adminer#151]
Trying to restore data into a production database from a backup.
Cant directly search for the rows I need. This requires a sub query to provide the correct id's to match the field on.

The subquery isn't executed and turns into a single value
![Screenshot from 2023-08-24 10-27-07](https://github.com/TimWolla/docker-adminer/assets/13876156/1a47c44e-4d80-4acc-82d1-9157b15240f6)

**Comment by TimWolla** [comment]
This is not an issue in this Docker image, but an issue in upstream Adminer. I cannot do anything about this.
