### ISSUE TITLE
None of the supported PHP extensions (mongo) are available.

### ISSUE THREAD

**Issue by babatundebusari** [TimWolla/docker-adminer#16]
how does one add PHP extensions when uding the official docker image?
tried to use mongodb but got this error

```
None of the supported PHP extensions (mongo) are available.
```

Thanks

**Comment by zzir** [comment]
https://store.docker.com/images/adminer?tab=description#supported-drivers

`docker exec -ti myadminer /bin/ash`

I went login root install PHP extensions of mongo.
`sudo pecl install mongo`

but
```
/var/www/html $ su -
su: must be suid to work properly
```

**Comment by TimWolla** [comment]
I just looked into the issue and noticed that the “mongo” extension does not work with PHP 7 any more. The newer “mongodb” extension OTOH is not supported by Adminer. You might consider filing a request to support the “mongodb” extension within Adminer itself: https://sourceforge.net/p/adminer/bugs-and-features/

Thus you won't be able to use MongoDB with this Docker image at this point in time.

**Comment by doreplado** [comment]
For anyone still looking for this, if you shell into the container (as root):
docker exec -ti -u root <your-container> sh

apk add autoconf gcc g++ make libffi-dev openssl-dev
pecl install mongodb
echo "extension=mongodb.so" > /usr/local/etc/php/conf.d/docker-php-ext-mongodb.ini
restart docker container.

**Comment by JedMeister** [comment]
@doreplado - thanks for that. I can confirm that your instructions resolved the `None of the supported PHP extensions (mongo) are available.` error. 

However, I still can't log in as now I'm getting a `Database does not support password.` error in Adminer. I can confirm that login using password works fine from the MongoDB commandline client. Any ideas?

**Comment by TimWolla** [comment]
> However, I still can't log in as now I'm getting a Database does not support password. error in Adminer. I can confirm that login using password works fine from the MongoDB commandline client. Any ideas?

This is a limitation of Adminer itself: https://github.com/vrana/adminer/blob/2780eb01f5b100a5b4657c4688b9f44d1ef825fe/adminer/drivers/mongo.inc.php#L627

**Comment by JedMeister** [comment]
@TimWolla - Thanks for the clarification.

I note that the [original bug report](https://sourceforge.net/p/adminer/bugs-and-features/571/) you linked to previously has been closed. 

I've documented my experiences as an [Adminer bug report](https://sourceforge.net/p/adminer/bugs-and-features/635/). I have added a comment to that bug report noting your point.

**Comment by TimWolla** [comment]
> I note that the original bug report you linked to previously has been closed.

Thanks for the heads up. I opened docker-library/docs#1292 to update the docs.

**Comment by TimWolla** [comment]
> I've documented my experiences as an Adminer bug report. I have added a comment to that bug report noting your point.

@JedMeister Looking at that again I believe that this is an **intentional** limitation: https://github.com/vrana/adminer/commit/60d1b7b3b4d21cf4428decd9b674a1b5b5495373

It appears that your MongoDB supports a log-in using both a password _and no password_. Or possibly the check in Adminer is a false-positive. In any case, I can't do anything about this :smile:

**Comment by cerino-ligutom** [comment]
Same situation as the [bug report](https://sourceforge.net/p/adminer/bugs-and-features/635/). Did this get fixed/patched or has any other workaround currently?

**Comment by TimWolla** [comment]
@cerino-ligutom Please check with the upstream bug tracker. I'm just packaging Adminer for Docker.

**Comment by cilf** [comment]
Looks like Adminer doesn't let you log in using credentials if it's also possible to log in without a password.

As a workaround, I created a docker image which removes the additional check for the empty password. More info in the gist itself

https://gist.github.com/cilf/017348bfbce87fb95ff61e295415a54f

**Comment by rickxz** [comment]
To anyone who might come here and want to use the awesome's @cilf workaround but with an updated adminer dockerfile, I made an updated version of his code (working on adminer:4.8.0 image) which is available in this gist:

https://gist.github.com/rickxz/e037248e6082c46295ff0d9e22314e30
