### ISSUE TITLE
increase → Unable to upload a file. Maximum allowed file size is 2MB.

### ISSUE THREAD

**Issue by roboto-cloud** [TimWolla/docker-adminer#17]
Solved!

I user this script inside Dockerfile:

```
# Store PHP Configs at /usr/local/etc/php/conf.d
RUN echo "upload_max_filesize = 500M" >> /usr/local/etc/php/conf.d/upload_large_dumps.ini \
    && echo "post_max_size = 500M"       >> /usr/local/etc/php/conf.d/upload_large_dumps.ini \
    && echo "memory_limit = -1"           >> /usr/local/etc/php/conf.d/upload_large_dumps.ini \
    && echo "max_execution_time = 0"      >> /usr/local/etc/php/conf.d/upload_large_dumps.ini

```
Regards,

**Comment by TimWolla** [comment]
For posterity: @roboto-cloud asked how to increase the maximum filesize for uploads (PHP's default is 2M). You can their good solution in their initial comment.

**Comment by davidhund** [comment]
More posterity 🤓

Sometimes we do not want/need to update the Dockerfile. 
E.g. when using it as a `docker-compose` service.

In a `docker-compose.yml` you can easily update the filesize limit by using an `uploads.ini` file as a _volume_:

```
# docker-compose.yml
[...]
   adminer:
     image: adminer
     volumes:
       - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
[...]
```

This way there's no need to update the Dockerfile/image.

**Comment by timwhite** [comment]
It may be good to document this somewhere better than an issue? Maybe in the README
