### ISSUE TITLE
Deprecation Notice?

### ISSUE THREAD

**Issue by tkbstudios** [TimWolla/docker-adminer#171]
Hello, I've been using adminer for quite some time. But what I don't accept is the fact that you're deprecating it/leaving it behind.
At the time of writing, the docker image has 100M+ pulls, a lot of people rely on it.  
You can't just kill such a widely-used project like this, it's going to cause possible problems on a large scale.

![image](https://github.com/user-attachments/assets/e4e31fe0-3e47-4d35-a364-62d79edba39b)

**Comment by TimWolla** [comment]
This is not my decision. I am just bundling the upstream project for use in Docker.
