### ISSUE TITLE
Plugins support

### ISSUE THREAD

**Issue by boldhedgehog** [TimWolla/docker-adminer#2]
Hi,
Can you modify the index.php to scan a ./plugin/ directory and enable all plugins in it? This way it can be mounted from the host, and anyone could use desired plugins.
If you work with Magento databases, the table filter plugin is a must.

**Comment by TimWolla** [comment]
I am willing to support that use case, but I have next to no experience
with adminer plugins. If you were able to create a Pull Request I'd be
happy to merge it. Otherwise I'll take a look at it when I have time, but
that might take longer.

Am 14.03.2017 10:53 schrieb "boldhedgehog" <notifications@github.com>:

**Comment by mikehaertl** [comment]
@TimWolla I can give this a try, if you want. 

Before I start, could you explain how you came up with the current code in `index.php`? It looks quite, uhm, unusual for PHP (in other words: hacky ;) ). Seems like it's only there to let the hostname default to "db". 

Two thoughts on that:

* It's only an assumption that "db" is the name of the database container. Is it really worth hacking the code to have this value prefilled?
* If yes, there's the `login-servers` plugin for predefined hostnames which we could use instead. It would limit the available host to some predefined names, though.

What we could do instead:

* Bundle all plugins that are included in the source release but disable them by default
* Add an env var to list plugins to enable, e.g. `ADMINER_PLUGINS='login-servers dump-json'`
* Add an env var for each plugin specific configuration (todo: needs more checks if this is feasible), e.g. `ADMINER_LOGIN_SERVERS='db myname myothername'`
* Additionally scan the `./plugins` directory for host mounted plugins
* Document how a user can override all of the plugin loading in cases where a more complex plugin configuration is required

**Comment by boldhedgehog** [comment]
@mikehaertl hi, just a reminder: https://www.adminer.org/en/plugins/
The `index.php` file in the docker image should be named `adminer.php`, and `index.php` should be a shell to load plugins, and then include the `adminer.php` main file.
```php
<?php
function adminer_object() {
    // required to run any plugin
    include_once "./plugins/plugin.php";
    
    // autoloader
    foreach (glob("plugins/*.php") as $filename) {
        include_once "./$filename";
    }
    
    $plugins = array(
        // specify enabled plugins here
        new AdminerDumpXml,
        new AdminerTinymce,
        new AdminerFileUpload("data/"),
        new AdminerSlugify,
        new AdminerTranslation,
        new AdminerForeignSystem,
    );
    
    /* It is possible to combine customization and plugins:
    class AdminerCustomization extends AdminerPlugin {
    }
    return new AdminerCustomization($plugins);
    */
    
    return new AdminerPlugin($plugins);
}

// include original Adminer or Adminer Editor
include "./adminer.php";
```

**Comment by mikehaertl** [comment]
@boldhedgehog Yes, I know. My question about `index.php` was referring to the current file in this repo: https://github.com/TimWolla/docker-adminer/blob/master/4.3/index.php

As you asked for plugin support, we should somehow automate loading of plugins.  I'm just not sure how to do that - and if it makes sense at all. But otherwhise you'd always have to create your custom `index.php`, list the plugins you want to use there and then map it into the container at runtime. If only adminer was a bit better designed in this regard. Honestly speaking there's much room for improvement in the overall coding style.

**Comment by TimWolla** [comment]
> Before I start, could you explain how you came up with the current code in index.php? It looks quite, uhm, unusual for PHP (in other words: hacky ;) ).

a) Subclassing the `\Adminer` class is the official way to customize adminer: https://www.adminer.org/de/extension/
b) I wanted a clean separation by using namespaces
c) I did not want to add a separate class file, just to fix the default host name.

> Seems like it's only there to let the hostname default to "db".

This is correct.

> It's only an assumption that "db" is the name of the database container. Is it really worth hacking the code to have this value prefilled?

Yes, my Docker image is opiniated in this regard by intent. The official examples in the README.md explicitely explain how to bind the database as `db`.

> It would limit the available host to some predefined names, though.

This is why I opted against that plugin. I wanted the flexibility in combination with the opiniated default, localhost simply does not make sense with regard to Docker.

<hr>

> Bundle all plugins that are included in the source release but disable them by default

Agreed.

> Add an env var to list plugins to enable, e.g. ADMINER_PLUGINS='login-servers dump-json'

Agreed, but error out if the plugin requires any parameters.

> Add an env var for each plugin specific configuration (todo: needs more checks if this is feasible), e.g. ADMINER_LOGIN_SERVERS='db myname myothername'

See one above this one.

> Additionally scan the ./plugins directory for host mounted plugins

Agreed.

> Document how a user can override all of the plugin loading in cases where a more complex plugin configuration is required

Agreed.

**Comment by mikehaertl** [comment]
> Yes, my Docker image is opiniated in this regard by intent.

Well, it's in some way not only your image anymore but the official adminer image now :). So IMO personal preference should not be the driving force, at least not if it requires such hacky measures. That code there messes around with the inner workings of adminer. And it adds a lot complexity for very little outcome . So if we want to implement the plugin feature it will get even more complex and harder to maintain.

I'd still say the correct and clean solution for this is to use the login-servers plugin. That's where you could put `db` as default and make it easily configurable to get the flexibility you want.

**Comment by TimWolla** [comment]
> at least not if it requires such hacky measures

I still refuse to call this solution “hacky”. I evaluated the login-servers plugin during creation of this Dockerfile, deemed it insufficient, because of the restricted list and thus created my solution. It provides a measurable benefit if you use the implicitly assumed name of the database container and is no less convenient than the old default of `localhost` if you don't.

> That code there messes around with the inner workings of adminer.

It does not. Overriding Adminer's methods is the canonical method to customize Adminer. The replaced part of the output is fairly specific, in order to not introduce unwanted side effects.

**Comment by mikehaertl** [comment]
@TimWolla Ok, but I feel it's better if you take over the implementation then. Our ideas of how this should look are too different and I want to avoid endless discussions.

One question though: Say someone wants to use the login-servers plugin. What's your idea how the servers should be configured?

**Comment by TimWolla** [comment]
> One question though: Say someone wants to use the login-servers plugin. What's your idea how the servers should be configured?

Not sure on that one, yet.

**Comment by TimWolla** [comment]
@boldhedgehog @mikehaertl I just created a PR: #5 I'll be glad if you'd test it and provide feedback.

**Comment by boldhedgehog** [comment]
@TimWolla tables filter plugin works for me; however, there is a typo in the README: all plugin files are with dashed, while the example command is with underscore, `tables_filter` should be changes to `tables-filter` here:
```bash
$ docker run --link some_database:db -p 8080:8080 -e ADMINER_PLUGINS='tables_filter tinymce' adminer
```

**Comment by TimWolla** [comment]
> however, there is a typo in the README

Good catch, fixed, thanks.
