### ISSUE TITLE
Update Docker image with bugfix in Tables Filter plugin

### ISSUE THREAD

**Issue by boldhedgehog** [TimWolla/docker-adminer#23]
Hi,

Can you update the Docker image anytime soon?
The image is built from the master branch of adminer, and sometimes there are not fixed bugs in it.
4 days ago a bug was fixed Tables Filter plugin https://github.com/vrana/adminer/commit/2dcad1f2847fa56839a635e20428c21c43a1c653 and I use the plugin on daily basis.

Thanks.

**Comment by TimWolla** [comment]
> Can you update the Docker image anytime soon?

No. This being an official image I only update to official releases of Adminer for two reasons:

1. Official images must be reproducible (thus pinned to a specific tag or commit).
2. They have to go through the official review process. See such a pull request here: https://github.com/docker-library/official-images/pull/3911

This combined requires work from two engineers which would be infeasible for every single commit. Updating for this issue would set a precedent I don't want to set. Also it would not be clear how the tag should be called in Docker Hub.

I suggest you to pin your adminer to `adminer:4.3.1-standalone` or `adminer:4.3.1-fastcgi`. These versions won't receive any more rebuilds (e.g. in case of security flaws of core alpine libraries), but that might work for adminer behind strong authorization.

**Comment by boldhedgehog** [comment]
Hi Tim,

Version 4.5.0 of adminer is released, when can it be expected in the official Docker repo?

**Comment by TimWolla** [comment]
@boldhedgehog Thanks for the heads up. I updated the image, it will appear in Docker Hub after docker-library/official-images#3947 is merged.
