### ISSUE TITLE
Improve slow shutdown

### ISSUE THREAD

**Issue by mikehaertl** [TimWolla/docker-adminer#3]
I found, that the image has quite a long shutdown times for me of > 10 seconds. It's probably a similar issue as described here: https://github.com/clue/docker-adminer/issues/17:

> Current form of CMD does not passes signals to the supervisord and container can not be stopped via standard docker stop command. After a timeout, container is killed by Docker.

I know that supervisord is not used here, but maybe the same problem exists for `php -S`.

**Comment by TimWolla** [comment]
Use the Docker 1.13 `--init` flag, please. See also the discussion for my other official image *spiped*: https://github.com/docker-library/docs/pull/814

I'm going to update the README files accordingly.

**Comment by TimWolla** [comment]
Correcting myself: I was able to fix the issue, without adding any additional executables. So I went for that one. I can recommend `--init` nonetheless.
