### ISSUE TITLE
fastcgi & container

### ISSUE THREAD

**Issue by Algedi13** [TimWolla/docker-adminer#32]
Hello, how to make it work with the container [docker-letsencrypt](https://github.com/linuxserver/docker-letsencrypt) in fastcgi please I can not do it

**Comment by TimWolla** [comment]
I don't know how you would add a new vHost to that Docker image (ask there, please). The required configuration would look something like this:

```
	index index.php;
	resolver 127.0.0.11;
	location ~ ^/(index.php)?$ {
		fastcgi_index index.php;
		include /etc/nginx/fastcgi_params;
		fastcgi_param  SCRIPT_FILENAME /var/www/html/index.php;
		fastcgi_param  DOCUMENT_ROOT   /var/www/html/;
		set $upstream adminer.service;
		fastcgi_pass $upstream:9000;
	}
```
