### ISSUE TITLE
Base URI or folder

### ISSUE THREAD

**Issue by lamuertepeluda** [TimWolla/docker-adminer#47]
Hi there,

is there any way to set a base URI or variable when deploying into a subfolder?

e.g. I have my docker running at `http://localhost:8080`, which is proxied using nginx to `https://mysite.whatever.com/my_folder/`

Now, I've noticed that this container redirects everything to `/`. 
All links in the dashboard are absolute and point to `https://mysite.whatever.com/?querystring` instead of `https://mysite.whatever.com/my_folder/?querystring`

Is there any env variable or configuration that can fix this behavior? Or is this an application issue?

I add the nginx.conf workaround which works mostly for the login, but does not work for some links, i.e.

```conf
     location /my_folder/ {
        proxy_pass http://127.0.0.1:8080/;
        proxy_redirect / /my_folder/;
    }
```

This works for the login because it doesn't get redirected to `/`, but correctly to `/my_folder/`

**Comment by TimWolla** [comment]
Duplicate of #14.
