### ISSUE TITLE
Add Ability To Change Ports

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [TimWolla/docker-adminer#48]
Please add the ability to change the listen ports on this image.

This could be done using environment variables i.e. WEB_PORT=12345 FASTCGI_PORT=67890

This would allow for easier spin-up and proxying of Adminer containers and would minimise port clashes.

Thanks!

**Comment by TimWolla** [comment]
I don't understand. The container runs in its own network namespace, thus it does not collide with other containers.

That being said: If you want to switch the port you can simply pass a custom command when starting the standalone container.  The port is not being referenced anywhere else:

https://github.com/TimWolla/docker-adminer/blob/0a5c6d6a531e35e2d20fdc97c87f57f5c1eaaa77/4/Dockerfile#L46

For fastcgi you would need to either `sed -i 's/9000/WHATEVER/' /usr/local/etc/php-fpm.d/zz-docker.conf` or load your custom configuration using a volume.

**Comment by danieledwardgeorgehitchcock** [comment]
Thanks for your reply.

Yes I understand that the container runs in its own network namespace however, if I had two containers running on the same port and then wished to reverse proxy both of them, I would get a clash hence the need to be able to change port.

**Comment by TimWolla** [comment]
> if I had two containers running on the same port and then wished to reverse proxy both of them, I would get a clash hence the need to be able to change port.

You would not get a clash. You can either specify the IP address of the container in your reverse proxy or specify a different host port when using Docker's port forwarding feature.

**Comment by danieledwardgeorgehitchcock** [comment]
So if the container is joined to the same network as another container running a service on port 8080 (say for example a network named reverse_proxy), the ports won't clash?

This isn't what I have experienced in my setup..

**Comment by TimWolla** [comment]
> So if the container is joined to the same network as another container running a service on port 8080 (say for example a network named reverse_proxy), the ports won't clash?

They won't. I run a bunch of services using the same port within a single Docker network in my machines.

> This isn't what I have experienced in my setup..

This is outside the scope of this repository then. Please seek support with Docker / file a bug with Docker.

**Comment by mangusbrother** [comment]
To add a usecase for this. 

Adminer could be run as a sidecar to another service at which point there will be a clash. 

Changing the port via environment variable is fairly standard behaviour, although the workaround you posted above works for now

**Comment by KingPin** [comment]
> To add a usecase for this.
> 
> Adminer could be run as a sidecar to another service at which point there will be a clash.
> 
> Changing the port via environment variable is fairly standard behaviour, although the workaround you posted above works for now

this is my usecase also, adminer is being run a large network with containers using network_mode to share a network. so 8080 definitely clashes for me.
