### ISSUE TITLE
Unable to load the login-password-less plugin

### ISSUE THREAD

**Issue by jbomaileva** [TimWolla/docker-adminer#50]
Hello !

We are trying to extend your image because we need to use the login-password-less plugin and it needs a custom file for the mandatory parameter.

Here is my Dockerfile :

```
FROM adminer:4.7.1-standalone
USER root
COPY login-password-less.php /var/www/html/plugins-enabled/login-password-less.php
USER adminer
```

And the content of login-password-less.php file :

```
<?php
require_once('plugins/login-password-less.php');

/** Set allowed password
	* @param string result of password_hash
	*/
return new AdminerLoginPasswordLess(
	$password_hash = "notthatvalue"
);
```

I set the env var ADMINER_PLUGINS to "login-password-less" but I still have this error on startup :

```
Unable to load plugin file "login-password-less", because it has required parameters: password_hash
Create a file "/var/www/html/plugins-enabled/login-password-less.php" with the following contents to load the plugin:

<?php
require_once('plugins/login-password-less.php');

/** Set allowed password
	* @param string result of password_hash
	*/
return new AdminerLoginPasswordLess(
	$password_hash = ???
);
```

Am I missing something ?

**Comment by TimWolla** [comment]
> Am I missing something ?

Yes. The `ADMINER_PLUGINS` environment variable is needed for the “autoloader” that set's up the file in `plugins-enabled` automatically. If you create the file yourself you must not add the plugin to the environment, because it would be overridden.

**Comment by ps-feng** [comment]
For the sake of completion, here's the `login-password-less.php` file that allows password-less access. For DBs without password, enter `admin` as the password.
```php
<?php
require_once('plugins/login-password-less.php');

/** Set allowed password
	* @param string result of password_hash
	*/
return new AdminerLoginPasswordLess(
	$password_hash = password_hash("admin", PASSWORD_DEFAULT)
);
```

**Comment by nerkn** [comment]
PASSWORD_DEFAULT is global php variable, or docker environment variable, or placeholder for us to change?

**Comment by TimWolla** [comment]
> PASSWORD_DEFAULT is global php variable, or docker environment variable, or placeholder for us to change?

That is a PHP constant to indicate the password hashing algorithm to use. Adminer expects a hashed password and that call will create a valid hash ad-hoc. As of right now `PASSWORD_DEFAULT` will result in a BCrypt hash:

```
php > var_dump(password_hash("admin", PASSWORD_DEFAULT));
php shell code:1:
string(60) "$2y$10$BsmC9NHuyjlOWyt9Q5FVA.WL/6lvZCZAdNF0wr9vLAA.s5SaU7xQq"
```
