### ISSUE TITLE
Cannot enter into container with bash

### ISSUE THREAD

**Issue by dhsrocha** [TimWolla/docker-adminer#54]
When I try `docker exec <some_adminer_container> bash_`, it prints:
> OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"bash_\": executable file not found in $PATH": unknown

**Comment by TimWolla** [comment]
This Docker image is based off alpine which does not ship bash by default. If you need a simple POSIX shell you can use `docker exec adminer sh`. If you need proper bash you can install it using:

```
FROM adminer
USER root
RUN apk add --no-cache bash
USER adminer
```
