### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by radoslav-stefanov** [TimWolla/docker-adminer#70]
Hey man, can you please bump this to 4.7.6? 

Thanks!

**Comment by TimWolla** [comment]
Already done since 4 hours: https://github.com/docker-library/official-images/pull/7387

**Comment by radoslav-stefanov** [comment]
@TimWolla  I just deployed using default image ```image: adminer```. It still pulls older version. I guess I'll try tagging newer version.

**Comment by TimWolla** [comment]
The pull request I linked needs to be merged by Docker Official Images team before the new version will be available on Docker Hub. See also this FAQ entry: https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what
