### ISSUE TITLE
Can you add pepa-linha-dark to the container?

### ISSUE THREAD

**Issue by STaRDoGG** [TimWolla/docker-adminer#71]
Looks like it's missing within the container itself:

![image](https://user-images.githubusercontent.com/1524526/73632677-1433e880-4622-11ea-8ca1-e34c733deac5.png)

So, instead of just being able to do a:

```
    environment:
      - ADMINER_DESIGN="pepa-linha-dark"
```

We have to manually copy the adminer.css to the container, which may get lost(?) of container updates, or have to create a mount just for that .css file. It'd be a lot easier to just be able to use the environment variable. =)

**Comment by TimWolla** [comment]
This Docker Image contains the designs that are part of the upstream repository: https://github.com/vrana/adminer/tree/master/designs. `pepa-linha-dark` is not one of those.

Thus you either have to build a custom image `FROM adminer` or bind mount the CSS into the container.

**Comment by STaRDoGG** [comment]
Strange thing is (and maybe it's just because I'm not a Linux expert) but I get a weird error when dealing with the adminer.css file.

For example, when I log into the adminer container and just try a `cat adminer.css`, I get this:

![image](https://user-images.githubusercontent.com/1524526/73692738-8811d780-469a-11ea-9d1e-a341373b3548.png)

If I try to directly bind mount the adminer.css to the `/var/www/html` folder:

`/c/Servers/Docker/Containers/Adminer/adminer.css:/var/www/html/adminer.css`

I get an error saying (paraphrasing): "adminer.css already exists".

Any ideas?

**Comment by TimWolla** [comment]
Please note that I'm not able to give extensive advice on operating Docker containers / Linux machines.

> For example, when I log into the adminer container and just try a `cat adminer.css`, I get this:

Based off the color I would assume that adminer.css is a symlink, in this case a symlink pointing to a non-existent file. You can use `ls -alh` or `readlink` to find out. I guess you specified `ADMINER_DESIGN=pepa-linha-dark`, it would possibly explain the issue.

> I get an error saying (paraphrasing): "adminer.css already exists".

I assume you specified `ADMINER_DESIGN` and creating the symlink within the start script fails because of the bind mount.

**Comment by STaRDoGG** [comment]
@TimWolla Thanks. You were correct in assuming I had that environment var set. I removed it and it did take care of the symlink.

I had originally also mounted the entire theme folder to the designs folder in the container, and then set that var to try to get this working, but it also didn't work.

That said, even removing the environment var didn't totally solve my issue. I still get a problem directly mounting the adminer.css, but it looks like it's due to me bumping into this issue now: *eyeroll*

https://github.com/docker/for-win/issues/5516
