### ISSUE TITLE
How to define a new port?

### ISSUE THREAD

**Issue by saxon-wu** [TimWolla/docker-adminer#77]
My database is postgresql and the port is 9999.
Login Adminer4.7.7 report such error: "SQLSTATE[08006] [7] could not connect to server: Connection refused Is the server running on host "postgresql" (120.240.95.33) and accepting TCP/IP connections on port 5432?".
I want to define the port:9999 in docker-compose.yml, how to do?

**Comment by TimWolla** [comment]
I expect that you would need to specify the database port during login as `postgres.example.com:9999`.

In any case this is not specific to this Docker Image, if you need support with Adminer itself please have a look at the official page: https://www.adminer.org/

**Comment by saxon-wu** [comment]
@TimWolla Yes, I can logined by typing XXX :9999 in the server input field.
Thank you!
