### ISSUE TITLE
how to connect sqlite db with adminer(docker version)

### ISSUE THREAD

**Issue by jet10000** [TimWolla/docker-adminer#78]
Is there a tutorial?

**Comment by TimWolla** [comment]
Load a PHP file `/var/www/html/plugins-enabled/sqlite.php` into the container with the following contents:

```
<?php
require("plugins/login-password-less.php");
// TODO: inline the result of password_hash() so that the password is not visible in source codes
return new AdminerLoginPasswordLess(password_hash("YOUR_PASSWORD_HERE", PASSWORD_DEFAULT));
```

see: https://github.com/vrana/adminer/blob/master/adminer/sqlite.php

If that does not work, please seek support at Adminer itself. Connecting to SQLite is not Docker specific.
