### ISSUE TITLE
Reduce logging verbosity

### ISSUE THREAD

**Issue by allen-ziegenfus** [TimWolla/docker-adminer#97]
Is there a way to configure adminer to not produce these constant log entries? Right now it's very verbose and makes it difficult to find relevant logs from other services

```
[::ffff:10.138.0.35]:36682 Accepted
[::ffff:10.138.0.35]:36682 [200]: GET /
[::ffff:10.138.0.35]:36682 Closing
```

**Comment by TimWolla** [comment]
Are those health checks? For actual use you shouldn't have constant log entries.

Anyway: That's from PHP's internal development webserver (https://www.php.net/manual/en/features.commandline.webserver.php). I'm using that one in Adminer for simplicity and it's perfectly fine for use within your local development environment.

If you want to use this Docker image within your production cluster then I recommend to use the FastCGI version of the Adminer in combination with a suitable FastCGI gateway (e.g. nginx). You can find proper nginx configurations in several issues within this repository.
